# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20190509_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Empregado',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='cliente',
            new_name='nomeEmpregado',
        ),
    ]
