# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20190509_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='departamentos',
            field=models.ManyToManyField(blank=True, to='clientes.Departamento'),
        ),
    ]
