# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20190509_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregado',
            name='funcao',
            field=models.CharField(default='rh', max_length=120),
            preserve_default=False,
        ),
    ]
